export const ADD_TODO = "ADD_TODO"
export const EDIT_TODO = "EDIT_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const TOGGLE_STATUS = "TOGGLE_STATUS"
export const ALL_CHECKED = "ALL_CHECKED"
export const FILTER_DATA = "FILTER_DATA"